config/routes.rb
Rails.application.routes.draw do
  root to: 'games#new'
  resources :games do
    resources :rooms, only: ['show']
  end
  resources :guesses, only: ['create', 'update']
  resources :accusations, only: ['create']
end

app/models/game.rb
class Game < ActiveRecord::Base
  after_create :deal

  has_one :answer, dependent: :destroy
  has_many :card_dealings, dependent: :destroy
  has_many :cards, through: :card_dealings
  has_many :players, dependent: :destroy

  def next_turn
    self.turn < self.players.length - 1 ? self.update(turn: self.turn + 1) : self.update(turn: 0)
  end
  private

  def deal
    suspects = Suspect.all
    rooms = Room.all
    weapons = Weapon.all

    # create players
    suspects.each do |suspect|
      self.players << Player.create(name: suspect.name, img: suspect.img, game_id: self.id)
    end

    # create random answer
    answer = Answer.create(game_id: self.id)

    who = suspects.shuffle.pop
    answer.card_dealings << CardDealing.create(card_id: who.id, game_id: self.id)
    where = rooms.shuffle.pop
    answer.card_dealings << CardDealing.create(card_id: where.id, game_id: self.id)
    how = weapons.shuffle.pop
    answer.card_dealings << CardDealing.create(card_id: how.id, game_id: self.id)

    # deal remaining cards to players
    cards = (suspects - [who]) + (rooms - [where]) + (weapons - [how])

    self.players.each do |player|
      3.times do
        card = cards.shuffle.pop
        player.card_dealings << CardDealing.create(card_id: card.id, game_id: self.id)
        cards = (cards - [card])
      end
      possible_cards = Card.all - player.cards
      possible_cards.each do |card|
        player.card_possibles << CardPossible.create(card_id: card.id)
      end
      player.current_room = rooms.sample
    end
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @game = Game.new()
    @suspects = Suspect.all
  end

  def create
    @game = Game.create()
    @player = @game.players.where(name: params['who']).first
    @player.update(user: true)
    @room = @player.current_room
    redirect_to game_room_path(@game, @room)
  end

  def update
    @game = Game.find(params[:id])
    @game.next_turn
    session[:return_to] ||= request.referer
    redirect_to session.delete(:return_to)
  end
end

app/views/games/_player.html.erb
<% if player == @player %>
  <% if @player.disprove_guess(guess) == false %>
    <%= javascript_tag "alert('You cannot disprove the guess. Pass?')" %>
    <h2><%= player.name %> passes.</h2>
  <% else %>
    <%= javascript_tag "alert('Reveal #{player.disprove_guess(guess).name}?')" %>
    <h2><%= player.name %> reveals <%= player.disprove_guess(guess).name %>.</h2>
  <% end %>
<% else %>
  <% if !player.disprove_guess(guess) %>
    <h2><%= player.name %> passes.</h2>
  <% else %>
    <h2><%= player.name %> reveals <%= player.disprove_guess(guess).name %>.</h2>
  <% end %>
<% end %>

app/views/games/new.html.erb
<h1>Get ready to play brain warp....</h1>

<div class="row">

  <% @suspects.each do |suspect| %>
    <%= link_to games_path(:who => suspect.name), method: 'post' do %>
      <div class="col-xs-2">
        <%= suspect %>
      </div>
    <% end %>
  <% end %>

</div>

<a href="/">I am a link!</a>