config/routes.rb
Rails.application.routes.draw do
  root to: 'games#new'
  resources :games do
    resources :rooms, only: ['show']
  end
  resources :guesses, only: ['create', 'update']
  resources :accusations, only: ['create']
end

app/models/room.rb
class Room < Card
  has_many :adjoining_rooms, :foreign_key => "room_id", :dependent => :destroy
  has_many :occurances_as_adjoining_room, :class_name => "AdjoiningRoom", :foreign_key => "next_room_id", :dependent => :destroy
  has_many :next_rooms, :through => :adjoining_rooms
  has_many :player_locations
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Card.find(params[:id])
    @game = Game.find(params[:game_id])
    @answer = @game.answer
    @player = @game.players.user
    @players = @game.players.order(:id)
    @current_player = @players[@game.turn]
    @current_player.take_turn
    @last_guess = @current_player.guesses.last
    @guess = Guess.new()
    3.times do @guess.card_selections.build end
    @accusation = Accusation.new()
    3.times do @accusation.card_selections.build end
  end
end

app/views/rooms/show.html.erb
<p>Welcome to the <%= @room %>, <%= @player %></p>


<p>Your cards are:
  <%= @player.cards.collect {|c| c}.to_sentence %>
</p>

<!-- <h2>Your possible suspects: <%= @player.possible_cards.suspects.collect {|c| c}.to_sentence %></h2>
<h2>Your possible rooms: <%= @player.possible_cards.rooms.collect {|c| c}.to_sentence %></h2>
<h2>Your possible weapons: <%= @player.possible_cards.weapons.collect {|c| c}.to_sentence %></h2> -->

<% if @current_player == @player %>
  <h2>Change Room:</h2>
  <% @room.next_rooms.each do |room| %>
  <div class="col-xs-4 text-center">
    <h4><%= link_to room, game_room_path(@game, room) %></h4>
  </div>
  <% end %>
  <br><br>

  <% if !@player.accusation %>
    <% if true %>
      <%= render 'guesses/form' %>
    <% end %>

    <% if true %>
      <%= render 'accusations/form' %>
    <% end %>
  <% end %>
<% else %>
  <div class="game_play">
    <h2 id="game_play"></h2>
    <h2 id="game_play2"></h2>
    <h2 id="game_play3"></h2>
    <!-- <h2><%= @current_player %> went into the <%= @current_player.current_room %>.</h2>
    <h2><%= @current_player %> guessed <%= @last_guess.cards.suspect %> in the <%= @last_guess.cards.room %> with the <%= @last_guess.cards.weapon %>.</h2> -->
  </div>
  <div class="game_play2">
    <h2 id="response1"></h2>
    <h2 id="response2"></h2>
  </div>
  <%= link_to 'Next', guess_path(@current_player.guesses.last), id: "update", :data => {:method => 'patch'}, remote: true  %>
  <!-- <div class="disprove">
    <%= disprove_guess(@current_player.next_player, @current_player.guesses.last) %>
  </div>
  <%= link_to 'Next', game_path(@game), :data => {:method => 'patch'} %> -->
<% end %>

answer and opponents cards:
<p>It was <%= @answer.cards.suspect %> in the <%= @answer.cards.room %>
with the <%= @answer.cards.weapon %></p>


<% @players.each do |player| %>
  <div class="col-xs-2">
  <li><%= player %></li>
  <ul>
  <% player.cards.each do |card| %>
  <li><%= card %></li>
  <% end %>
  </ul>
  </div>
<% end %>


<script type="text/javascript">
$(document).ready(function($){
  $("#game_play").lbyl({
      content: "It is <%= @current_player.name %>'s turn.",
      speed: 25,
      finished: function() {
       $("#game_play2").lbyl({
          content: "<%= @current_player.name %> went into the <%= @current_player.current_room.name %>.",
          speed: 25,
          finished: function() {
            $("#game_play3").lbyl({
              content: "<%= @current_player.name %> guessed <%= @current_player.guesses.last.cards.suspect.name %> in the <%= @players[@game.turn].guesses.last.cards.room.name %> with the <%= @players[@game.turn].guesses.last.cards.weapon.name %>.",
              speed: 25
            });
          }
       });
     }
  });
  $(window).keypress(function (e) {
    if (e.keyCode === 0 || e.keyCode === 32) {
      $('a#update').trigger('click');
    }
  });
});
</script>